from rdflib.namespace import XSD

CHAR_FIRST = {"name" : "hasName", 
            #   "info" : , 
              "url" : "hasUrl"}

EPS_FIRST = ["title", "info", "characters", "url"]

CHAR_INFO = {
    'Residence': 'residesAt', 
    'Occupation(s)': 'hasOccupation', 
    'Gender': 'hasGender', 
    'Classification': 'ClassifiesAs', 
    'First appearance': 'firstAppearanceOn', 
    'Portrayer': 'hasPortrayer', 
    'Color': 'hasColor', 
    'Eye color': 'hasEyeColor', 
    'Children': 'hasChildren', 
    'Parents': 'hasParents', 
    'Spouse': 'hasSpouse', 
    'Latest appearance': 'latestAppearanceOn', 
    'Appearance': 'hasAppearance'
    }

CHAR_INFO_LITERAL = {
    'Residence': 'residesAt', 
    'Occupation(s)': 'hasOccupation', 
    'Gender': 'hasGender', 
    'Classification': 'ClassifiesAs', 
    'Color': 'hasColor', 
    'Eye color': 'hasEyeColor'
    }

CHAR_INFO_LITERAL_TYPES = {key: XSD.string for key in CHAR_INFO_LITERAL}

CHAR_INFO_CHAR = {
    'Children': 'hasChildren', 
    'Parents': 'hasParents', 
    'Spouse': 'hasSpouse',
    }

CHAR_INFO_EPS = {
    'First appearance': 'firstAppearanceOn', 
    'Latest appearance': 'latestAppearanceOn', 
    'Appearance': 'hasAppearance'
    }

CHAR_INFO_PASS = {
    'Performed by'
    }

EPS_INFO_LITERAL = {
    "Production code": "hasProductionCode",
    "Season №": "onSeasonNo",
    "Episode №": "hasEpisodeNo",
    "Airdate": "hasAirdate",
    "U.S. premiere time (ET)": "hasPremiereTime",
    "Copyright year": "hasCopyrightYear",
    "U.S. viewers (millions)": "HasViewers",
    "Running time": "hasRunningTime",
}

EPS_INFO_LITERAL_TYPES = {
    "Production code": XSD.string,
    "Season №": XSD.integer,
    "Episode №": XSD.string,
    "Airdate": XSD.date,
    "U.S. premiere time (ET)": XSD.time,
    "Copyright year": XSD.gYear,
    "U.S. viewers (millions)": XSD.decimal,
    "Running time": XSD.duration,
}

EPS_INFO_NODES = {
    "Writer(s)": "hasWriters",
    "Storyboard Artist(s)": "hasStoryboardArtists",
    "Storyboard": "hasStoryboard",
    "Animation": "hasAnimators",
    "Creative": "hasCreatives",
    "Guest(s)": "hasGuests",
    "Supervising": "hasSupervisor",
    "Line Producer": "hasLineProducer",
    "Main": "hasMain",
    "Supervising Producer(s)": "hasSupervisingProducers",
    "Technical": "hasTechnicals",
    "Animation Supervisor": "hasAnimationSupervisor",
}

EPS_INFO_EPS = {
    'Sister episode(s)': 'hasSisterEpisodes',
    'Next': 'hasNextEpisode', 
    'Previous': 'hasPreviousEpisode'
    }

EPS_DICT = {
    "Help Wanted": "1a",
    "Reef Blower": "1b",
    "Tea at the Treedome": "1c",
    "Bubblestand": "2a",
    "Ripped Pants": "2b",
    "Jellyfishing": "3a",
    "Plankton!": "3b",
    "Naughty Nautical Neighbors": "4a",
    "Boating School": "4b",
    "Pizza Delivery": "5a",
    "Home Sweet Pineapple": "5b",
    "Mermaid Man and Barnacle Boy": "6a",
    "Pickles": "6b",
    "Hall Monitor": "7a",
    "Jellyfish Jam": "7b",
    "Sandy's Rocket": "8a",
    "Squeaky Boots": "8b",
    "Nature Pants": "9a",
    "Opposite Day": "9b",
    "Culture Shock": "10a",
    "F.U.N.": "10b",
    "MuscleBob BuffPants": "11a",
    "Squidward the Unfriendly Ghost": "11b",
    "The Chaperone": "12a",
    "Employee of the Month": "12b",
    "Scaredy Pants": "13a",
    "I Was a Teenage Gary": "13b",
    "SB-129": "14a",
    "Karate Choppers": "14b",
    "Sleepy Time": "15a",
    "Suds": "15b",
    "Valentine's Day": "16a",
    "The Paper": "16b",
    "Arrgh!": "17a",
    "Rock Bottom": "17b",
    "Texas": "18a",
    "Walking Small": "18b",
    "Fools in April": "19a",
    "Neptune's Spatula": "19b",
    "Hooky": "20a",
    "Mermaid Man and Barnacle Boy II": "20b",
    "Your Shoe's Untied": "21a",
    "Squid's Day Off": "21b",
    "Something Smells": "22a",
    "Bossy Boots": "22b",
    "Big Pink Loser": "23a",
    "Bubble Buddy": "23b",
    "Dying for Pie": "24a",
    "Imitation Krabs": "24b",
    "Wormy": "25a",
    "Patty Hype": "25b",
    "Grandma's Kisses": "26a",
    "Squidville": "26b",
    "Prehibernation Week": "27a",
    "Life of Crime": "27b",
    "Christmas Who?": "28",
    "Survival of the Idiots": "29a",
    "Dumped": "29b",
    "No Free Rides": "30a",
    "I'm Your Biggest Fanatic": "30b",
    "Mermaid Man and Barnacle Boy III": "31a",
    "Squirrel Jokes": "31b",
    "Pressure": "32a",
    "The Smoking Peanut": "32b",
    "Shanghaied": "33a",
    "Gary Takes a Bath": "33b",
    "Welcome to the Chum Bucket": "34a",
    "Frankendoodle": "34b",
    "The Secret Box": "35a",
    "Band Geeks": "35b",
    "Graveyard Shift": "36a",
    "Krusty Love": "36b",
    "Procrastination": "37a",
    "I'm with Stupid": "37b",
    "Sailor Mouth": "38a",
    "Artist Unknown": "38b",
    "Jellyfish Hunter": "39a",
    "The Fry Cook Games": "39b",
    "Squid on Strike": "40a",
    "Sandy, SpongeBob, and the Worm": "40b",
    "The Algae's Always Greener": "41a",
    "SpongeGuard on Duty": "41b",
    "Club SpongeBob": "42a",
    "My Pretty Seahorse": "42b",
    "Just One Bite": "43a",
    "The Bully": "43b",
    "Nasty Patty": "44a",
    "Idiot Box": "44b",
    "Mermaid Man and Barnacle Boy IV": "45a",
    "Doing Time": "45b",
    "Snowball Effect": "46a",
    "One Krabs Trash": "46b",
    "As Seen on TV": "47a",
    "Can You Spare a Dime?": "47b",
    "No Weenies Allowed": "48a",
    "Squilliam Returns": "48b",
    "Krab Borg": "49a",
    "Rock-a-Bye Bivalve": "49b",
    "Wet Painters": "50a",
    "Krusty Krab Training Video": "50b",
    "Party Pooper Pants": "51",
    "Chocolate with Nuts": "52a",
    "Mermaid Man and Barnacle Boy V": "52b",
    "New Student Starfish": "53a",
    "Clams": "53b",
    "Ugh": "54",
    "The Great Snail Race": "55a",
    "Mid-Life Crustacean": "55b",
    "Born Again Krabs": "56a",
    "I Had an Accident": "56b",
    "Krabby Land": "57a",
    "The Camping Episode": "57b",
    "Missing Identity": "58a",
    "Plankton's Army": "58b",
    "The Sponge Who Could Fly": "59",
    "SpongeBob Meets the Strangler": "60a",
    "Pranks a Lot": "60b",
    "Fear of a Krabby Patty": "61a",
    "Shell of a Man": "61b",
    "The Lost Mattress": "62a",
    "Krabs vs. Plankton": "62b",
    "Have You Seen This Snail?": "63",
    "Skill Crane": "64a",
    "Good Neighbors": "64b",
    "Selling Out": "65a",
    "Funny Pants": "65b",
    "Dunces and Dragons": "66",
    "Enemy In-Law": "67a",
    "Mermaid Man & Barnacle Boy VI: The Motion Picture": "67b",
    "Patrick SmartPants": "68a",
    "SquidBob TentaclePants": "68b",
    "Krusty Towers": "69a",
    "Mrs. Puff, You're Fired": "69b",
    "Chimps Ahoy": "70a",
    "Ghost Host": "70b",
    "Whale of a Birthday": "71a",
    "Karate Island": "71b",
    "All That Glitters": "72a",
    "Wishing You Well": "72b",
    "New Leaf": "73a",
    "Once Bitten": "73b",
    "Bummer Vacation": "74a",
    "Wigstruck": "74b",
    "Squidtastic Voyage": "75a",
    "That's No Lady": "75b",
    "The Thing": "76a",
    "Hocus Pocus": "76b",
    "Driven to Tears": "77a",
    "Rule of Dumb": "77b",
    "Born to Be Wild": "78a",
    "Best Frenemies": "78b",
    "The Pink Purloiner": "79a",
    "Squid Wood": "79b",
    "Best Day Ever": "80a",
    "The Gift of Gum": "80b",
    "Friend or Foe": "81",
    "The Original Fry Cook": "82a",
    "Night Light": "82b",
    "Rise and Shine": "83a",
    "Waiting": "83b",
    "Fungus Among Us": "83c",
    "Spy Buddies": "84a",
    "Boat Smarts": "84b",
    "Good Ol' Whatshisname": "84c",
    "New Digs": "85a",
    "Krabs à la Mode": "85b",
    "Roller Cowards": "86a",
    "Bucket Sweet Bucket": "86b",
    "To Love a Patty": "87a",
    "Breath of Fresh Squidward": "87b",
    "Money Talks": "88a",
    "SpongeBob vs. The Patty Gadget": "88b",
    "Slimy Dancing": "88c",
    "The Krusty Sponge": "89a",
    "Sing a Song of Patrick": "89b",
    "A Flea in Her Dome": "90a",
    "The Donut of Shame": "90b",
    "The Krusty Plate": "90c",
    "Goo Goo Gas": "91a",
    "Le Big Switch": "91b",
    "Atlantis SquarePantis": "92",
    "Picture Day": "93a",
    "Pat No Pay": "93b",
    "BlackJack": "93c",
    "Blackened Sponge": "94a",
    "Mermaid Man vs. SpongeBob": "94b",
    "The Inmates of Summer": "95a",
    "To Save a Squirrel": "95b",
    "Pest of the West": "96",
    "20,000 Patties Under the Sea": "97a",
    "The Battle of Bikini Bottom": "97b",
    "What Ever Happened to SpongeBob?": "98",
    "The Two Faces of Squidward": "99a",
    "SpongeHenge": "99b",
    "Banned in Bikini Bottom": "100a",
    "Stanley S. SquarePants": "100b",
    "House Fancy": "101a",
    "Krabby Road": "101b",
    "Penny Foolish": "102a",
    "Nautical Novice": "102b",
    "Spongicus": "103a",
    "Suction Cup Symphony": "103b",
    "Not Normal": "104a",
    "Gone": "104b",
    "The Splinter": "105a",
    "Slide Whistle Stooges": "105b",
    "A Life in a Day": "106a",
    "Sun Bleached": "106b",
    "Giant Squidward": "107a",
    "No Nose Knows": "107b",
    "Patty Caper": "108a",
    "Plankton's Regular": "108b",
    "Boating Buddies": "109a",
    "The Krabby Kronicle": "109b",
    "The Slumber Party": "110a",
    "Grooming Gary": "110b",
    "SpongeBob SquarePants vs. The Big One": "111",
    "Porous Pockets": "112a",
    "Choir Boys": "112b",
    "Krusty Krushers": "113a",
    "The Card": "113b",
    "Dear Vikings": "114a",
    "Ditchin'": "114b",
    "Grandpappy the Pirate": "115a",
    "Cephalopod Lodge": "115b",
    "Squid's Visit": "116a",
    "To SquarePants or Not to SquarePants": "116b",
    "Shuffleboarding": "117a",
    "Professor Squidward": "117b",
    "Pet or Pests": "118a",
    "Komputer Overload": "118b",
    "Gullible Pants": "119a",
    "Overbooked": "119b",
    "No Hat for Pat": "120a",
    "Toy Store of Doom": "120b",
    "Sand Castles in the Sand": "121a",
    "Shell Shocked": "121b",
    "Chum Bucket Supreme": "122a",
    "Single Cell Anniversary": "122b",
    "Truth or Square": "123-124",
    "Pineapple Fever": "125a",
    "Chum Caverns": "125b",
    "The Clash of Triton": "126",
    "Tentacle-Vision": "127a",
    "I ♥ Dancing": "127b",
    "Growth Spout": "128a",
    "Stuck in the Wringer": "128b",
    "Someone's in the Kitchen with Sandy": "129a",
    "The Inside Job": "129b",
    "Greasy Buffoons": "130a",
    "Model Sponge": "130b",
    "Keep Bikini Bottom Beautiful": "131a",
    "A Pal for Gary": "131b",
    "Yours, Mine and Mine": "132a",
    "Kracked Krabs": "132b",
    "The Curse of Bikini Bottom": "133a",
    "Squidward in Clarinetland": "133b",
    "SpongeBob's Last Stand": "134",
    "Back to the Past": "135a",
    "The Bad Guy Club for Villains": "135b",
    "A Day Without Tears": "136a",
    "Summer Job": "136b",
    "One Coarse Meal": "137a",
    "Gary in Love": "137b",
    "The Play's the Thing": "138a",
    "Rodeo Daze": "138b",
    "Gramma's Secret Recipe": "139a",
    "The Cent of Money": "139b",
    "The Monster Who Came to Bikini Bottom": "140a",
    "Welcome to the Bikini Bottom Triangle": "140b",
    "The Curse of the Hex": "141a",
    "The Main Drain": "141b",
    "Trenchbillies": "142a",
    "Sponge-Cano!": "142b",
    "The Great Patty Caper": "143",
    "That Sinking Feeling": "144a",
    "Karate Star": "144b",
    "Buried in Time": "145a",
    "Enchanted Tiki Dreams": "145b",
    "The Abrasive Side": "146a",
    "Earworm": "146b",
    "Hide and Then What Happens?": "147a",
    "Shellback Shenanigans": "147b",
    "The Masterpiece": "148a",
    "Whelk Attack": "148b",
    "You Don't Know Sponge": "149a",
    "Tunnel of Glove": "149b",
    "Krusty Dogs": "150a",
    "The Wreck of the Mauna Loa": "150b",
    "New Fish in Town": "151a",
    "Love That Squid": "151b",
    "Big Sister Sam": "152a",
    "Perfect Chemistry": "152b",
    "Accidents Will Happen": "153a",
    "The Other Patty": "153b",
    "Drive Thru": "154a",
    "The Hot Shot": "154b",
    "A Friendly Game": "155a",
    "Sentimental Sponge": "155b",
    "Frozen Face-Off": "156",
    "Squidward's School for Grown-Ups": "157a",
    "Oral Report": "157b",
    "Sweet and Sour Squid": "158a",
    "The Googly Artiste": "158b",
    "A SquarePants Family Vacation": "159",
    "Patrick's Staycation": "160a",
    "Walking the Plankton": "160b",
    "Mooncation": "161a",
    "Mr. Krabs Takes a Vacation": "161b",
    "Ghoul Fools": "162",
    "Mermaid Man Begins": "163a",
    "Plankton's Good Eye": "163b",
    "Barnacle Face": "164a",
    "Pet Sitter Pat": "164b",
    "House Sittin' for Sandy": "165a",
    "Smoothe Jazz at Bikini Bottom": "165b",
    "Bubble Troubles": "166a",
    "The Way of the Sponge": "166b",
    "The Krabby Patty That Ate Bikini Bottom": "167a",
    "Bubble Buddy Returns": "167b",
    "Restraining SpongeBob": "168a",
    "Fiasco!": "168b",
    "Are You Happy Now?": "169a",
    "Planet of the Jellyfish": "169b",
    "Free Samples": "170a",
    "Home Sweet Rubble": "170b",
    "Karen 2.0": "171a",
    "InSPONGEiac": "171b",
    "Face Freeze!": "172a",
    "Glove World R.I.P.": "172b",
    "Squiditis": "173a",
    "Demolition Doofus": "173b",
    "Treats!": "174a",
    "For Here or to Go": "174b",
    "It's a SpongeBob Christmas!": "175",
    "Super Evil Aquatic Villain Team Up is Go!": "176a",
    "Chum Fricassee": "176b",
    "The Good Krabby Name": "177a",
    "Move It or Lose It": "177b",
    "Hello Bikini Bottom!": "178",
    "Extreme Spots": "179a",
    "Squirrel Record": "179b",
    "Patrick-Man!": "180a",
    "Gary's New Toy": "180b",
    "License to Milkshake": "181a",
    "Squid Baby": "181b",
    "Little Yellow Book": "182a",
    "Bumper to Bumper": "182b",
    "Eek, an Urchin!": "183a",
    "Squid Defense": "183b",
    "Jailbreak!": "184a",
    "Evil Spatula": "184b",
    "It Came from Goo Lagoon": "185",
    "Safe Deposit Krabs": "186a",
    "Plankton's Pet": "186b",
    "Don't Look Now": "187a",
    "Séance Shméance": "187b",
    "Kenny the Cat": "188a",
    "Yeti Krabs": "188b",
    "SpongeBob You're Fired": "189",
    "Lost in Bikini Bottom": "190a",
    "Tutor Sauce": "190b",
    "Squid Plus One": "191a",
    "The Executive Treatment": "191b",
    "Company Picnic": "192a",
    "Pull Up a Barrel": "192b",
    "Sanctuary!": "193a",
    "What's Eating Patrick?": "193b",
    "Patrick! The Game": "194a",
    "The Sewers of Bikini Bottom": "194b",
    "SpongeBob LongPants": "195a",
    "Larry's Gym": "195b",
    "The Fish Bowl": "196a",
    "Married to Money": "196b",
    "Mall Girl Pearl": "197a",
    "Two Thumbs Down": "197b",
    "Sharks vs. Pods": "198a",
    "CopyBob DittoPants": "198b",
    "Sold!": "199a",
    "Lame and Fortune": "199b",
    "Goodbye, Krabby Patty?": "200",
    "Sandy's Nutmare": "201a",
    "Bulletin Board": "201b",
    "Food Con Castaways": "202a",
    "Snail Mail": "202b",
    "Pineapple Invasion": "203a",
    "Salsa Imbecilicus": "203b",
    "Mutiny on the Krusty": "204a",
    "The Whole Tooth": "204b",
    "Whirly Brains": "205a",
    "Mermaid Pants": "205b",
    "Unreal Estate": "206a",
    "Code Yellow": "206b",
    "Mimic Madness": "207a",
    "House Worming": "207b",
    "Snooze You Lose": "208a",
    "Krusty Katering": "208b",
    "SpongeBob's Place": "209a",
    "Plankton Gets the Boot": "209b",
    "Life Insurance": "210a",
    "Burst Your Bubble": "210b",
    "Plankton Retires": "211a",
    "Trident Trouble": "211b",
    "The Incredible Shrinking Sponge": "212a",
    "Sportz?": "212b",
    "The Getaway": "213a",
    "Lost and Found": "213b",
    "Patrick's Coupon": "214a",
    "Out of the Picture": "214b",
    "Feral Friends": "215a",
    "Don't Wake Patrick": "215b",
    "Cave Dwelling Sponge": "216a",
    "The Clam Whisperer": "216b",
    "Spot Returns": "217a",
    "The Check-Up": "217b",
    "Spin the Bottle": "218a",
    "There's a Sponge in My Soup": "218b",
    "Man Ray Returns": "219a",
    "Larry the Floor Manager": "219b",
    "The Legend of Boo-Kini Bottom": "220",
    "No Pictures Please": "221a",
    "Stuck on the Roof": "221b",
    "Krabby Patty Creature Feature": "222a",
    "Teacher's Pests": "222b",
    "Sanitation Insanity": "223a",
    "Bunny Hunt": "223b",
    "Squid Noir": "224a",
    "Scavenger Pants": "224b",
    "Cuddle E. Hugs": "225a",
    "Pat the Horse": "225b",
    "Chatterbox Gary": "226a",
    "Don't Feed the Clowns": "226b",
    "Drive Happy": "227a",
    "Old Man Patrick": "227b",
    "Fun-Sized Friends": "228a",
    "Grandmum's the Word": "228b",
    "Doodle Dimension": "229a",
    "Moving Bubble Bass": "229b",
    "High Sea Diving": "230a",
    "Bottle Burglars": "230b",
    "My Leg!": "231a",
    "Ink Lemonade": "231b",
    "Mustard O' Mine": "232a",
    "Shopping List": "232b",
    "Whale Watching": "233a",
    "Krusty Kleaners": "233b",
    "Patnocchio": "234a",
    "ChefBob": "234b",
    "Plankton Paranoia": "235a",
    "Library Cards": "235b",
    "Call the Cops": "236a",
    "Surf N' Turf": "236b",
    "Goons on the Moon": "237",
    "Appointment TV": "238a",
    "Karen's Virus": "238b",
    "The Grill is Gone": "239a",
    "The Night Patty": "239b",
    "Bubbletown": "240a",
    "Girls' Night Out": "240b",
    "Squirrel Jelly": "241a",
    "The String": "241b",
    "FarmerBob": "242a",
    "Gary & Spot": "242b",
    "The Nitwitting": "243a",
    "The Ballad of Filthy Muck": "243b",
    "The Krusty Slammer": "244a",
    "Pineapple RV": "244b",
    "Gary's Got Legs": "245a",
    "King Plankton": "245b",
    "Plankton's Old Chum": "246a",
    "Stormy Weather": "246b",
    "Swamp Mates": "247a",
    "One Trick Sponge": "247b",
    "The Krusty Bucket": "248a",
    "Squid's on a Bus": "248b",
    "Sandy's Nutty Nieces": "249a",
    "Insecurity Guards": "249b",
    "Broken Alarm": "250a",
    "Karen's Baby": "250b",
    "Shell Games": "251a",
    "Senior Discount": "251b",
    "Mind the Gap": "252a",
    "Dirty Bubble Returns": "252b",
    "Jolly Lodgers": "253a",
    "Biddy Sitting": "253b",
    "SpongeBob's Big Birthday Blowout": "254-255",
    "SpongeBob in RandomLand": "256a",
    "SpongeBob's Bad Habit": "256b",
    "Handemonium": "257a",
    "Breakin'": "257b",
    "Boss for a Day": "258a",
    "The Goofy Newbie": "258b",
    "The Ghost of Plankton": "259a",
    "My Two Krabses": "259b",
    "Knock Knock, Who's There?": "260a",
    "Pat Hearts Squid": "260b",
    "Lighthouse Louie": "261a",
    "Hiccup Plague": "261b",
    "A Cabin in the Kelp": "262a",
    "The Hankering": "262b",
    "Who R Zoo?": "263a",
    "Kwarantined Krab": "263b",
    "Plankton's Intern": "264a",
    "Patrick's Tantrum": "264b",
    "Bubble Bass's Tab": "265a",
    "Kooky Cooks": "265b",
    "Escape from Beneath Glove World": "266",
    "Krusty Koncessionaires": "267a",
    "Dream Hoppers": "267b",
    "A Place for Pets": "268a",
    "Lockdown for Love": "268b",
    "Under the Small Top": "269a",
    "Squidward's Sick Daze": "269b",
    "Goofy Scoopers": "270a",
    "Pat the Dog": "270b",
    "Something Narwhal This Way Comes": "271a",
    "C.H.U.M.S": "271b",
    "SpongeBob's Road to Christmas": "272",
    "Potato Puff": "273a",
    "There Will Be Grease": "273b",
    "The Big Bad Bubble Bass": "274a",
    "Sea-Man Sponge Haters Club": "274b",
    "Food PBFFT! Truck": "275a",
    "Upturn Girls": "275b",
    "Say Awww!": "276a",
    "Patrick the Mailman": "276b",
    "Captain Pipsqueak": "277a",
    "Plane to Sea": "277b",
    "Squidferatu": "278a",
    "Slappy Daze": "278b",
    "Welcome to Binary Bottom": "279a",
    "You're Going to Pay...Phone": "279b",
    "A Skin Wrinkle in Time": "279c",
    "Abandon Twits": "280a",
    "Wallhalla": "280b",
    "Salty Sponge": "281a",
    "Karen for Spot": "281b",
    "Arbor Day Disarray": "282a",
    "Ain't That the Tooth": "282b",
    "Ma and Pa's Big Hurrah": "283a",
    "Yellow Pavement": "283b",
    "The Flower Plot": "284a",
    "SpongeBob on Parade": "284b",
    "Delivery to Monster Island": "285a",
    "Ride Patrick Ride": "285b",
    "Hot Crossed Nuts": "286a",
    "Sir Urchin and Snail Fail": "286b",
    "Friendiversary": "287a",
    "Mandatory Music": "287b",
    "Dopey Dick": "288a",
    "Plankton and the Beanstalk": "288b",
    "My Friend Patty": "289a",
    "FUN-Believable": "289b",
    "Spatula of the Heavens": "290a",
    "Gary's Playhouse": "290b",
    "Swimming Fools": "291a",
    "The Goobfather": "291b",
    "SquidBird": "292a",
    "Allergy Attack!": "292b",
    "Big Top Flop": "293a",
    "Sandy, Help Us!": "293b",
    "Single-Celled Defense": "294a",
    "Buff for Puff": "294b",
    "We ♥ Hoops": "295a",
    "SpongeChovy": "295b",
    "BassWard": "296a",
    "Squidiot Box": "296b",
    "Blood is Thicker Than Grease": "297a",
    "Don't Make Me Laugh": "297b",
    "Momageddon": "298a",
    "Pet the Rock": "298b",
    "Tango Tangle": "299a",
    "Necro-Nom-Nom-Nom-I-Con": "299b",
    "PL-1413": "300a",
    "In the Mood to Feud": "300b",
    "Mooned!": "301a",
    "Hysterical History": "301b",
    "Kreepaway Kamp": "302-303",
    "The Dirty Bubble Bass": "304a",
    "Sheldon SquarePants": "304b",
    "Sammy Suckerfish": "305a",
    "Big League Bob": "305b",
    "Snow Yellow and the Seven Jellies": "306"
}

CHARS = {
	"French_Narrator",
	"Sea_urchin",
	"Gary_the_Snail",
	"Shelley",
	"Patrick_Star",
	"Squidward_Tentacles",
	"Incidental_30",
	"Incidental_30A",
	"Betsy_Krabs",
	"Reef_blower",
	"Scallops_and_clams",
	"Fred",
	"Incidental_2",
	"Incidental_3",
	"Jellyfish",
	"Lavender_jellyfish",
	"Sandy_Cheeks",
	"Giant_clam",
	"Sandys_orange_bird",
	"Duck_bubble",
	"Elephant_bubble",
	"SpongeBobs_swim_trunks",
	"Larry_the_Lobster",
	"Chef",
	"Announcer_fish",
	"Steven",
	"John",
	"Tom",
	"Incidental_7",
	"Incidental_8",
	"Incidental_9",
	"Incidental_10",
	"Priscilla",
	"Incidental_13",
	"Incidental_14",
	"Incidental_15",
	"Incidental_16",
	"Incidental_17",
	"Incidental_18",
	"Incidental_19",
	"Incidental_20",
	"Incidental_21",
	"Carol",
	"Incidental_23",
	"Incidental_24",
	"Incidental_24A",
	"Incidental_27",
	"Incidental_28",
	"Incidental_29",
	"Incidental_31",
	"Don_the_Whale",
	"Incidental_34",
	"Incidental_35",
	"Harold",
	"Tuck_Tucker",
	"Scooter",
	"Lou",
	"Harold",
	"Incidental_41",
	"Judy",
	"Incidental_46",
	"Sadie",
	"Incidental_48",
	"Incidental_49",
	"Frank",
	"Loser_incidentals",
	"Carol",
	"Loser_2",
	"Frank",
	"Queen_jellyfish",
	"Sheldon_J_Plankton",
	"Karen_Plankton",
	"The_Alphabet_Song",
	"Planktons_lab",
	"Chum_Bucket_glove",
	"Mrs_Puff",
	"Incidental_25",
	"Joe",
	"Incidental_50",
	"Pioneers",
	"Swordfish_trucker",
	"Customer",
	"Nematodes",
	"Harold_SquarePants",
	"Margaret_SquarePants",
	"Herb_Star",
	"Baby_fish",
	"Barnacle_Boy",
	"Clam_Head_Candy_Cad",
	"King_Neptune",
	"Man_Ray",
	"Mermaid_Man",
	"Orderly",
	"Old_sailor",
	"The_chief",
	"Realistic_Fish_Head",
	"Incidental_80",
	"Incidental_81",
	"Incidental_81B",
	"Incidental_82",
	"Old_Man_Walker",
	"Incidental_83B",
	"Incidental_82",
	"Incidental_85",
	"Old_Man_Jenkins",
	"Mary",
	"Incidental_88",
	"Incidental_88C",
	"Incidental_89",
	"Incidental_90",
	"Incidental_91",
	"Incidental_92",
	"Incidental_92B",
	"Incidental_93",
	"Victoria_Ellen",
	"Cafeteria_lady_1",
	"Cafeteria_lady_2",
	"Bubble_Bass",
	"Troutenheimer",
	"Incidental_42",
	"Incidental_60",
	"Incidental_61",
	"Incidental_62",
	"Incidental_63",
	"Incidental_64",
	"Billy",
	"Incidental_67",
	"Incidental_68",
	"Incidental_69",
	"Incidental_70",
	"Incidental_71",
	"Harris",
	"Mailman",
	"Motorist",
	"Cop_incidentals",
	"Incidental_118",
	"Incidental_118",
	"Incidental_118",
	"Incidental_118",
	"Jellyfish",
	"Live_action_dolphins",
	"Scallops_and_clams",
	"Granny_Tentacles",
	"Flats_the_Flounder",
	"Pearl_Krabs",
	"Incidental_33",
	"Mr_Doodles",
	"Squeaky_boots",
	"Money",
	"Cindy",
	"Incidental_11",
	"Fire_fish",
	"Scallops_and_clams",
	"Seahorse",
	"Incidental_49A",
	"Scallops_and_clams",
	"Bubble_hippo",
	"Incidental_95",
	"F_incidentals",
	"Fred",
	"Incidental_2",
	"Incidental_F3",
	"Incidental_F4",
	"Incidental_F5",
	"Incidental_F6",
	"Incidental_23",
	"Incidental_F8",
	"Incidental_F9",
	"Incidental_F10",
	"Incidental_F11",
	"Incidental_F12",
	"Incidental_F13",
	"Incidental_10",
	"Incidental_15",
	"Incidental_F16",
	"Eugene",
	"Incidental_F18",
	"Incidental_F19",
	"Incidental_30A",
	"Incidental_F21",
	"Incidental_F22",
	"Incidental_F23",
	"Incidental_F24",
	"Male_cowfish",
	"Female_cowfish",
	"City_crowds",
	"Incidental_34",
	"Lenny",
	"Incidental_115",
	"Incidental_118",
	"Incidental_city_crowd_incidentals",
	"Incidental_157",
	"Incidental_city_crowd_2",
	"Incidental_city_crowd_3",
	"Shark_nerd",
	"Incidental_24B",
	"Incidental_24C",
	"Incidental_24D",
	"Incidental_24E",
	"Incidental_24F",
	"Incidental_24Q",
	"Incidental_41",
	"Measuring_fish_inc",
	"Crowd_incidentals",
	"Crowd_1",
	"Crowd_2",
	"Crowd_3",
	"Squidwards_bonsai",
	"Flying_Dutchman",
	"Incidental_30",
	"Seagull",
	"Sponge_dummy",
	"Margie_Star",
	"Long_Tan_and_Handsome",
	"Octavius_Rex",
	"Incidental_1B",
	"Clint",
	"Teen_incidentals",
	"Billy_Fishkins",
	"Teen_1A",
	"Bryan_Flounder",
	"Teen_2A",
	"Teen_3",
	"Teen_3A",
	"Billy_Fishkin",
	"Teen_4A",
	"Teen_5",
	"Teen_5A",
	"Teen_6",
	"Teen_6A",
	"Teen_6B",
	"Cindy",
	"Teen_8",
	"Teen_9",
	"Incidental_7",
	"Teen_12",
	"Teen_13",
	"Incidental_8",
	"Teen_15",
	"Teen_B1",
	"Teen_B6",
	"Football_player",
	"Norman_Rockbass",
	"Employee_of_the_Month_SpongeBobs",
	"Incidental_43",
	"Incidental_44",
	"Incidental_45",
	"Incidental_51",
	"Incidental_52",
	"Incidental_53",
	"Incidental_56",
	"Kid",
	"Mom",
	"Dad",
	"Homeowner",
	"Incidental_116",
	"Scallops_and_clams",
	"SpongeTron",
	"486_SpongeTron_clones",
	"Incidental_119",
	"PatTron",
	"Nautilus",
	"Primitive_SpongeBob",
	"Primitive_Patrick",
	"Jay_Lender",
	"The_Alone_Group",
	"Volcano_Sauce_drop",
	"Tom_Kenny",
	"Royal_fish",
	"Parakeet",
	"Moby_Dollar",
	"Incidental_120",
	"Incidental_121",
	"Incidental_122",
	"Incidental_123",
	"Incidental_124",
	"Incidental_125",
	"Incidental_126",
	"Incidental_127",
	"Incidental_128",
	"Incidental_129",
	"Incidental_130",
	"Incidental_131",
	"Incidental_132",
	"Incidental_133",
	"Incidental_134",
	"Incidental_135",
	"Incidental_136",
	"Incidental_137",
	"Incidental_33",
	"Incidental_66",
	"Incidental_116",
	"Scallops_and_clams",
	"Hans",
	"Peter_Bennett",
	"Guy_in_shower",
	"Chocolate_eating_scallops",
	"Balloon_stand_fish",
	"Heart_man",
	"Kid_fish_at_park",
	"Incidental_96",
	"Incidental_97",
	"Incidental_98",
	"Incidental_99",
	"Incidental_100",
	"Incidental_101",
	"Incidental_102",
	"Incidental_103",
	"Incidental_104",
	"Frank",
	"Incidental_106",
	"Steve",
	"Dale",
	"Incidental_109",
	"Incidental_110",
	"Incidental_111",
	"Incidental_112",
	"Incidental_113",
	"Incidental_139",
	"Incidental_142",
	"Incidental_143",
	"Incidental_144",
	"Mr_Paper",
	"Lil_Squidward",
	"Merriwether_Williams",
	"Carolyn_Lawrence",
	"Jill_Talley",
	"Lori_Alan",
	"Incidental_41",
	"Incidental_200",
	"Incidental_201",
	"Incidental_202",
	"Incidental_204",
	"Incidental_205",
	"Incidental_206",
	"Bert",
	"Jojo",
	"Incidental_214",
	"Incidental_220",
	"Incidental_221",
	"Incidental_222",
	"Soil",
	"Three_baby_fish",
	"Grandpa_SquarePants",
	"Flats_the_Flounder",
	"Eel",
	"Octopus_vendor",
	"Little_girl",
	"Goo_Lagoon",
	"Mrs_Tentacles",
	"Harold",
	"Poseidome_Colosseum",
	"Fishermen",
	"John_Lurie",
	"Jim_Jarmusch",
	"New_incidental",
	"Fish_Hooks_Park",
	"Jumbo_Shrimp",
	"Sinister_Slug",
	"Atomic_Flounder",
	"Mailman",
	"Dirty_Bubble",
	"Dancing_anemone",
	"Human_football_players",
	"Harold",
	"Priscilla",
	"Incidental_165",
	"Sea_creature",
	"Painty_the_Pirate",
	"Painted_parrot",
	"Alternate_Universe_SpongeBob_SquarePants",
	"Mrs_Crossing_Guard",
	"Marching_band",
	"Didgeridoo_player",
	"Alternate_Universe_SpongeBob_SquarePants",
	"Smaller_mailman",
	"Agnes",
	"Lady",
	"Lenny",
	"Incidental_115",
	"Incidental_118",
	"Incidental_141",
	"Mr_Mailman",
	"Man_inc_hat",
	"Purple_leech_creature",
	"The_Ugly_Barnacle",
	"Scooter",
	"Incidental_150",
	"Octopus",
	"Davy_Jones",
	"Sea_unicorn",
	"Mr_Mailman",
	"Incidental_119",
	"Sadie",
	"Bubble_Buddy",
	"Criminal",
	"Incidental_104",
	"Incidental_20",
	"Incidental_23",
	"Incidental_106",
	"Steve",
	"Grubby_Grouper",
	"Drink_vendor",
	"Pirates",
	"Pirate_1",
	"Pirate_2",
	"Captain_Cruel",
	"Pirate_4",
	"Incidental_49A",
	"Tuck_Tucker",
	"Robot_game_show_host",
	"Head_enhanced_fish",
	"Robot_Krabs",
	"Snakey",
	"Birdy",
	"Wormy",
	"Lou",
	"Incidental_157",
	"Sea_spider",
	"Frank",
	"Incidental_152",
	"Sandals",
	"Band_incidentals",
	"Conductor_1",
	"Drummer_2",
	"Clarinet_player_3",
	"Tuba_player_4",
	"Sax_player_5",
	"Flute_player_6",
	"Trombone_player_7",
	"Trumpet_player_8",
	"Amoeba",
	"Sea_leprechaun",
	"Grandma_SquarePants",
	"Incidental_23A",
	"Spokesman",
	"Groundskeeper",
	"Squid_guard_1",
	"Orville",
	"Squid_incidentals",
	"Squid_man_1",
	"Squid_man_2",
	"Squid_man_3",
	"Squid_woman_4",
	"Squid_woman_5",
	"Squidette",
	"Kid_playing_in_sand",
	"Camper",
	"Female_skier",
	"Male_skier",
	"Giant_clam",
	"Real_life_drummer",
	"Aaron_Springer",
	"Elephant_fish",
	"Crustacean_Crime_Theater",
	"Bad_Crab",
	"Incidental_118",
	"Muscle_guy",
	"Alan_Smart",
	"Patchy_the_Pirate",
	"Potty_the_Parrot",
	"Pottys_puppeteer",
	"Elves",
	"Santa_Claus",
	"Genie",
	"Incidental_46",
	"Reindeer",
	"Sheriff_Sandy",
	"Dirty_Dan",
	"Pinhead_Larry",
	"Rex",
	"Larry_the_Snail",
	"Jerry",
	"Incidental_118D",
	"Boaty",
	"Bikini_Bottom_jail_warden",
	"Kevin_C_Cucumber",
	"Incidental_151",
	"Jellyfish_geek_G_incidentals",
	"Jellyfish_geek_G1",
	"Jellyfish_geek_G2",
	"Jellyfish_geek_G3",
	"Jellyfish_geek_G4",
	"Jellyfish_geek_G5",
	"Jellyfish_geek_G6",
	"Jellyfish_geek_G7",
	"Jellyfish_geek_G9",
	"Jellyfish_geek_G10",
	"Jellyfish_geek_G11",
	"Carl",
	"Jellyfish_geek_G13",
	"Jellyfish_geek_G14",
	"Jellyfish_geek_G15",
	"Jellyfish_geek_G16",
	"Jellyfish_geek_G17",
	"Jellyfish_geek_G18",
	"Jellyfish_geek_G19",
	"Jellyspotter_incidentals",
	"Incidental_30",
	"Incidental_30A",
	"Incidental_30",
	"Incidental_30A",
	"Incidental_30A",
	"Dr_Manowar",
	"Big_Lenny",
	"Jeffrey_the_Jellyfish",
	"King_jellyfish",
	"Incidental_81A",
	"Dougie_Williams",
	"Flea",
	"Incidental_38A",
	"Krabs_family",
	"Clamu",
	"Incidental_153",
	"Baby_Oyster",
	"Mrs_Dutchman",
	"Fly_of_Despair",
	"Mohawk_brute_1",
	"Perfume_department",
	"Chimpanzees",
	"Subliminal_message_girl",
	"Thaddeus_Paul_Couldron",
	"Robot_SpongeBob",
	"Artist",
	"Seagull",
	"Doodle_jellyfish",
	"Magic_mustache",
	"Squid_Doodle",
	"DoodleBob",
	"Squidward_Tentacles_house",
	"Squilliam_Fancyson",
	"Fire_fish",
	"The_hash_slinging_slasher",
	"Richard",
	"Nosferatu",
	"Mr_Puff",
	"Waiter_incidentals",
	"Teen_5",
	"Teen_5",
	"Teen_5",
	"Squid_massage_therapist",
	"Mr_Sun",
	"Scallops_and_clams",
	"Clock",
	"SpongeBob_SquarePants_house",
	"Marty",
	"Janet",
	"Captain_Cruel",
	"Old_Man_Jenkins",
	"Mom_octopus",
	"Octopus_quintuplets",
	"Monty_P_Moneybags",
	"Friend",
	"Huge_guy",
	"Incidental_103",
	"Alaskan_Bull_Worm",
	"Fred",
	"Moat_fish",
	"Old_fisherman",
	"Pa_Cheeks",
	"Alternate_Universe_Squidward",
	"Shrimp",
	"Fredrick",
	"Pearl_Plankton",
	"Planktons_cousins",
	"Shark_mom",
	"Shark_son",
	"Shark_daughter",
	"Seamonster",
	"Orca_kid",
	"Magic_Conch_shell",
	"Ranger",
	"Mystery_the_Seahorse",
	"Victor_Krabs",
	"Baby_Squid_Burger",
	"Flats_dad",
	"Health_inspector",
	"Fake_health_inspector",
	"Officer_Nancy",
	"Cockroaches",
	"Mabel",
	"Anchovies",
	"Old_Man_Jenkins",
	"Officer_Nancy",
	"Incidental_160",
	"Prison_guard_1",
	"Prison_guard_2",
	"FP_incidentals",
	"Incidental_FP1",
	"Incidental_FP2",
	"Incidental_FP3",
	"Incidental_FP4",
	"Incidental_FP5",
	"Incidental_FP6",
	"Incidental_FP7",
	"Incidental_FP8",
	"Incidental_FP9",
	"MayorJudge",
	"Donna",
	"Fisherwoman_whale",
	"Capn_Humboldt_Squid",
	"One_eyed_prisoner",
	"Finback_prisoner",
	"Crowd",
	"Female_collector",
	"Owl_clam",
	"Black",
	"Smitty_Werbenjägermanjensen",
	"Army_of_the_Living_Dead",
	"Worker_fish",
	"Short_construction_worker",
	"Tool_belt_worker",
	"Showgirl_fish",
	"Clown",
	"Business_man",
	"New_narrator",
	"Puppets",
	"The_Salty_Spitoon",
	"Popeye_fish",
	"Greaser_fish",
	"Finback_fish",
	"Hate_fish",
	"Tattoo_thug",
	"Tough_guy_fish",
	"Bubba_fish",
	"Gaptooth_thug",
	"Belt_buckle_thug",
	"Reg",
	"Nerd_1",
	"Johnson",
	"Animatronic_server",
	"Drifter",
	"Bryan_Flounder",
	"The_Appetizer",
	"Clever_Visual_Metaphor_for_the_Abstract_Concept_of_Thought",
	"Robot",
	"Sherm_SquarePants",
	"Jeff_Tentacles",
	"DJ",
	"Bikini_Bottom_News",
	"Junior",
	"Worm",
	"Narrator",
	"Giraffe",
	"Hoopla",
	"Minnie_Mermaid",
	"Longbeard",
	"Fisherman",
	"Barnacle_Bill",
	"Saltwater_Sam_feat_the_Brine_Brothers",
	"The_Bird_Brains",
	"Female_parrots",
	"Bikini_Bottom_Police_Department",
	"Incidental_118C",
	"Barnacle_Chips",
	"Baby_Prunes",
	"Sea_star",
	"Miss_Appear",
	"Elastic_Waistband",
	"Captain_Magma",
	"The_Quickster",
	"The_Adventures_of_Mermaid_Man_and_Barnacle_Boy",
	"Roger",
	"Seahorse",
	"Good_Noodle_Board",
	"Live_action_orchestra",
	"Steven",
	"Old_Bluelip",
	"Bronty_the_Patchysaurus",
	"Bill_Fagerbakke",
	"Rodger_Bumpass",
	"Doug_Lawrence",
	"Dee_Bradley_Baker",
	"Sirena_Irwin",
	"Cavey",
	"SpongeGar",
	"Prehistoric_Krabs",
	"Dorudon",
	"Prehistoric_Gary",
	"Squog",
	"Patar",
	"Amoeba",
	"Patchys_mother",
	"X_29488",
	"Tyrannosaurus_Rex",
	"Snellie",
	"Strongman_Powder",
	"Rocky",
	"Incidental_13",
	"Larry_Luciano",
	"Youre_Old",
	"Martin_Olson",
	"Scout",
	"Victoria_Ellen",
	"Hot_rod_chick",
	"Hot_rod_dude",
	"Foggy_Patty",
	"Pinch_o_Matic",
	"Chip",
	"Penny",
	"Used_Napkin",
	"Gorilla",
	"George",
	"Scott_Heathcote",
	"Dale_Waddington_Horowitz",
	"Roxanne_Sarlak",
	"Christian_Trimble",
	"Incidental_67",
	"Incidental_91",
	"Incidental_48",
	"Blue_kid_fish",
	"Klaus",
	"Mohawk_brute_2",
	"Sea_bear",
	"Fake_Science_Monthly",
	"Chimpanzees",
	"Sea_rhinoceros",
	"Waitress",
	"Ted",
	"Snail_Po",
	"Bank_robber",
	"Stingray_5000",
	"Planktons_robot",
	"Plankton_family",
	"PKTN_30",
	"PKTN_33",
	"PKTN_29",
	"Clem",
	"Rufus_Plankton",
	"Rainchild",
	"Nickelodeon_Animation_Studio",
	"Mrs_Johnson",
	"Stephen_Hillenburg",
	"Billy_Bob_Star",
	"Incidental_CM19",
	"Dennis",
	"Annette",
	"Ted",
	"Kent_Matthew_Osborne",
	"Tattletale_Strangler",
	"Tough_Tavern",
	"Starfish_thug",
	"Incidental_102",
	"Patty",
	"Navy_Buddies",
	"Iron_Eye",
	"Mutton_Chop",
	"Torpedo_Belly",
	"Lockjaw_Jones",
	"Barnacles",
	"Navy_captain",
	"Incidental_185",
	"Navy_3",
	"Navy_inc",
	"Muscle_extra_1",
	"Muscle_extra_2",
	"Muscle_Fish_4",
	"Unknown_Navy_1",
	"Unknown_Navy_2",
	"Unknown_Navy_3",
	"Unknown_Navy_4",
	"Unknown_Navy_5",
	"Unknown_Navy_6",
	"Unknown_Navy_7",
	"Unknown_Navy_8",
	"Mattresses__Then_Some_employee",
	"Doctor_1",
	"Doctor_2",
	"JK",
	"Nurse",
	"Administrator_Flotsam",
	"Blood_worm",
	"Richard_A_Bottomfeeder",
	"Judge_Stickleback",
	"Granny_Plankton",
	"Miss_Tuffsy",
	"Scary_snails",
	"GrandmaGrammaGranny",
	"Picture_framed_snails",
	"Garys_Song",
	"Incidental_41",
	"Skill_crane",
	"Bikini_Bottom_Construction_Company",
	"Construction_foreman",
	"Worker_fish",
	"Inc_fish_soldier",
	"Angry_resident_fish",
	"Howard_Blandy",
	"Peterson",
	"Hook_Museum",
	"HR_thug",
	"GrammaGrandma",
	"Doctor_2",
	"Incidental_41A",
	"Incidental_64A",
	"Morrie",
	"Queen",
	"Knights",
	"Dungeon_master",
	"Squidly_Tentacles",
	"Dragon_jellyfish",
	"King_Krabs",
	"Princess_Pearl_Krabs",
	"Leech",
	"Executioners",
	"Planktonamor_Plankton",
	"Blacksmith",
	"Karen_the_Crystal_Ball",
	"Sandy",
	"Planktonamors_guards",
	"Chumbot",
	"The_Krusty_Krab",
	"Kelp_Thing",
	"The_Mermaid_Man_and_Barnacle_Boy_Fan_Club",
	"Jellyfish_geek_G5",
	"Jellyfish_geek_G6",
	"Jellyfish_geek_G3",
	"Jellyfish_geek_G7",
	"Jellyfish_geek_G4",
	"Jellyfish_geek_G9",
	"Jellyfish_geek_G13",
	"Jellyfish_geek_G2",
	"Jellyfish_geek_G1",
	"Mermaid_Man_and_Barnacle_Boy_actors",
	"Male_alien",
	"Female_alien",
	"Mary",
	"Therapist",
	"Fused_together_characters",
	"Cashier_2",
	"Mrs_Tentacles_house",
	"Mr_Fitz",
	"Sergeant_Roderick",
	"Goofy_Goober",
	"Fully_Automated_Nutcracker",
	"Dr_Marmalade",
	"Lord_Reginald",
	"Professor_Percy",
	"Fat_ghost",
	"Colored_ghost",
	"Motorcycle_ghost",
	"Rollerblading_monks",
	"Zeke_the_Sheik",
	"Boys_Who_Cry",
	"Judy",
	"Incidental_174",
	"Billy_Fishkins",
	"Cashier",
	"Mrs_Poecilia",
	"Master_Udon",
	"Karate_Islands_best_fighters",
	"The_Tickler",
	"Lipp_Cervas",
	"Filthy_Phil",
	"Pat_Morita",
	"Chubby_customer",
	"SpongeBobs_spatula",
	"Le_Spatula",
	"Perch_Perkins",
	"Female_inc",
	"Orange_guy",
	"Purple_guy",
	"Ned_and_the_Needlefish",
	"Milo_J_Fingerfish",
	"Salesman",
	"Mr_Seaweed",
	"Fancy_dandy_fish",
	"Kelpy_G",
	"SWAT_Team",
	"Smellies",
	"Mr_Magic",
	"Squidward_the_Ice_Cream_Cone",
	"Horace_B_Magic",
	"Motorcycle_guy",
	"Minister",
	"King_Amoeba",
	"Maw_Tucket",
	"Prince_Callous",
	"Prince_Dingus",
	"Princess_Tulsa",
	"Queen_Mildew",
	"Sluggo_Star",
	"Yorick",
	"Mattresses__Then_Some_employee",
	"Alternate_Universe_Patrick",
	"Bikini_Bottom_Bad_Boys",
	"Walter_Haddock",
	"Mild_Ones",
	"Kelpshake_cashier",
	"HAZMAT_Unit",
	"Blue_crested_blaster",
	"Speckled_squirter",
	"Two_fisted_jumper",
	"Gold_throated_singer",
	"Confess_a_Bear",
	"Mini_Squidward",
	"Incidental_92C",
	"Milo_J_Finkerfish",
	"Mini_SpongeBob",
	"Usher",
	"Puppet_usher",
	"Harold",
	"Patricks_underwear",
	"Robo_21",
	"Trucker",
	"Mr_Pirateson",
	"Patchy_Patty",
	"Frank",
	"Incidental_91",
	"Billy",
	"Incidental_K2",
	"Big_Johnny",
	"Billy",
	"Incidental_K6",
	"Nursery",
	"Sea_snail",
	"Balloon_vendor",
	"Stinky",
	"Rat",
	"Jim",
	"Guard",
	"Bodyguard",
	"Derek_Iversen",
	"The_Moth",
	"Alarm_Clock",
	"Pillow_SpongeBob",
	"SWAT_Team",
	"HAZMAT_nurse",
	"Hazmat_doctor",
	"Fancy_fish",
	"Patrick_clones",
	"Tom",
	"Mr_What_Zit_Tooya",
	"Bikini_Bottom_Hockey_Team",
	"Delicious_dairy_treat",
	"Realistic_Fish_Head",
	"Death",
	"Glovey_Glove",
	"Incidental_159",
	"Dale",
	"Lenny",
	"Happy_gland",
	"Business_man",
	"Incidental_41",
	"Ghost_incidentals",
	"Ghost_1",
	"Ghost_2",
	"Ghost_5",
	"Ghost_6",
	"Unknown_Ghost_1",
	"Unknown_Ghost_2",
	"Unknown_Ghost_3",
	"Unknown_Ghost_4",
	"Money",
	"Lady",
	"Patty_Gadget",
	"John",
	"Harris",
	"Troutenheimer",
	"Angry_Jack",
	"Agnes",
	"Judge_3",
	"Tutu_whale",
	"Quarter_guy",
	"Pedro",
	"Gene_Scallop",
	"Bob_Preflumster",
	"Barbara",
	"Musician_3",
	"Mabel",
	"Horace_A_Whopper",
	"Near_Mint_Comic_Books_cashier",
	"Coach",
	"Unnamed_band",
	"Nerd_1",
	"Billy",
	"Angel_donut",
	"Devil_donut",
	"Ma_Plankton",
	"Incidental_2",
	"Tom",
	"Incidental_7",
	"Harold",
	"Incidental_41",
	"Sadie",
	"Incidental_63",
	"Incidental_64",
	"Steve",
	"Incidental_118D",
	"Incidental_151",
	"Mr_Le_Schnook_Luigi",
	"Mr_Crustacean",
	"Underbite_worker",
	"Paul_Tibbitt",
	"Captain_of_the_Sea_Ship_Atlantis",
	"Atlantean_citizens",
	"Lord_Royal_Highness",
	"Nando",
	"Aggressive_Case_of_the_Sniffles",
	"Germs",
	"SpongeBot_SteelPants",
	"Party_snails",
	"Encino",
	"Vulture",
	"Norblock_Five",
	"Tom",
	"Green_kid_fish",
	"Balding_guy",
	"Mrs_Puffs_Boating_School",
	"BlackJack",
	"Captain_Blue_SquarePants",
	"BlackJacks_guard_worm",
	"Jack_M_Crazyfish",
	"Jellyfish_geek_G19",
	"Carol",
	"Harris",
	"Camp_Counselor_Kraus",
	"Octopus_quintuplets",
	"Barney",
	"Bernie",
	"Warden",
	"Giant_clam",
	"Patrick_Revere",
	"Great_Great_Grandpa_Krabs",
	"Rosie_Cheeks",
	"Clint",
	"Family_Histories_of_Bikini_Bottom",
	"Family_Histories_of_Bikini_Bottom",
	"SpongeBuck_SquarePants",
	"Undertaker",
	"Hopalong_Squidward",
	"Polene_Puff",
	"Pappy_Krabs",
	"Tapey",
	"Pecos_Patrick",
	"Dead_Eye_Plankton",
	"Cowbones",
	"Sea_monster",
	"Old_Man_Walker",
	"Sandys_robot",
	"Mr_and_Mrs_Dollar",
	"Gaptooth_thug",
	"Jellyfish_geek_G15",
	"Carl",
	"Jellyfish_geek_G10",
	"Incidental_CM13",
	"Bass_player",
	"Triton",
	"The_Bubble_Poppin_Boys",
	"Keyboardist",
	"Drummer",
	"Balding_guy",
	"Big_fish",
	"Purple_teen_fish",
	"Big_fish_four_eyes",
	"King_Poseidon",
	"Sparky",
	"Luna",
	"Stone_SpongeBob",
	"SpongeHenge",
	"Aliens",
	"Miss_Gristlepuss",
	"Miss_Gristlepuss_Sisters",
	"Al_Gristlepuss",
	"Stanley_S_SquarePants",
	"Bikini_Bottom_Construction_Company",
	"Sandys_cousin",
	"Squidwards_teenage_cousin",
	"Mr_Krabs_three_nephews",
	"SpongeBobs_spatula",
	"Nicholas_Withers",
	"Bikini_Bottom_Police_Department",
	"Squidwards_toilet",
	"SpongeBobs_brain",
	"Lion_fish",
	"Anchovies",
	"Maestro",
	"Billy_Fishkin",
	"Video_narrator",
	"Mr_Normal",
	"Sea_monkey",
	"K_9_Unit",
	"SWAT_Team",
	"Trench_monsters",
	"Craig_Mammalton",
	"Don_the_Whale",
	"Don",
	"Squidwards_lawyers",
	"Nautical_Mart",
	"Patricks_nose",
	"Surgeon",
	"Joe",
	"Highway_Speed_Patrol",
	"Fish_cowboy",
	"Sewer_monster",
	"Pole",
	"The_Neptunian_Science_Committee",
	"Slumber_Party_Zombie_Attack",
	"Bass_player",
	"Girly_Teengirl",
	"Sea_snail",
	"Muffsies_the_Snail",
	"Unknown_Snail_1",
	"Fancy_guy",
	"Foofie",
	"Mrs_Squiggles",
	"Incidental_F6s_worm",
	"Snail_1",
	"Krusty_Krab_cash_register",
	"Eddie",
	"Big_G",
	"Silent_Stan",
	"Twitch",
	"Jack_Kahuna_Laguna",
	"Krabs_family",
	"The_Big_One",
	"AppraiserPawn_Shop_owner",
	"Scallops_and_clams",
	"Jeeves",
	"Patrick_and_Garys_family",
	"Steve",
	"Jim",
	"Champ_2",
	"Iron_buns",
	"Mr_Fluffy",
	"Robber",
	"Quincy",
	"Chieftain",
	"Helga",
	"Gordon",
	"Viking_incidentals",
	"Olaf",
	"Olaf",
	"Olaf",
	"Olaf",
	"Olaf",
	"Olaf",
	"Viking_9",
	"Viking_12",
	"Olaf",
	"Olaf",
	"Olaf",
	"Mr_Mailman",
	"Octopus_quintuplets",
	"Redbeard_Krabs",
	"Kraken",
	"Cephalopod_Lodge_members",
	"Leader",
	"Cantankerous_Moray_Eelius",
	"Incidental_85",
	"Commissioner",
	"Music_School_Matron",
	"Incidental_118A",
	"Spotted_glistening_meadow_worms",
	"Mrs_Wormsley",
	"King_Neptunes_mother",
	"T119_A_Compumatic",
	"Noxious_Enterprises_SuperSPU_31_Liquid_Cooled_Mobile_Processing_Unit",
	"Command_Module",
	"Bakery_fish",
	"SpongeBob_SquarePants_clones",
	"Boy_fish",
	"Krabs_family",
	"Dad_fish",
	"Sand_gargoyles",
	"Sand_knight",
	"Sand_army",
	"Sand_general",
	"Sea_snail",
	"Mini_Brain_Patricks",
	"Patricks_forehead",
	"Chum_Bucket",
	"EMILP",
	"Ricky_Gervais",
	"Party_Pooper_Pants",
	"The_Sponge_Who_Could_Fly",
	"Tyrannosaurus_Rex",
	"Security_guard",
	"Johnny_Depp",
	"Incidental_CM24",
	"BargN_Mart",
	"The_Guy_on_the_Penny",
	"Pnk",
	"Live_action_whale",
	"Not_SpongeBob",
	"Unnamed_band",
	"Judge_3",
	"Wedding_official",
	"Rubber_Hose_Rag",
	"Cave_dwellers",
	"Chum_Caverns",
	"Queen_Amphitrite",
	"Zeus",
	"TV_producer",
	"Moat_fish",
	"Agent_fish",
	"Twin_sisters",
	"Leftover",
	"Chopped_liver",
	"Peanut_worms",
	"SpongeBobs_heart",
	"Catfish",
	"Health_inspector",
	"Mr_Krabs_pet_scallop",
	"Balding_guy",
	"Fresh_and_Natural_Sponge",
	"Bikini_Bottom_Television",
	"Casting_director",
	"Burly_woman",
	"Fortune_teller",
	"Mr_Doodles",
	"Puffy_Fluff_incidentals",
	"Puffy_Fluff_1",
	"Puffy_Fluff_2",
	"Puffy_Fluffy",
	"League_of_Cheapskate_Crabs",
	"Penny_Pinchers",
	"Beuford_BargainBottom",
	"Dwight_T_Wad",
	"Chintzy_McGee",
	"Giant_bell_hop",
	"Dennis",
	"The_Flying_Dutchmans_date",
	"Corporal_Sterling",
	"Eagle_head",
	"Pressure",
	"Mr_Ranger",
	"Singing_coral",
	"Mr_Mayor",
	"Clown",
	"Santa_fish",
	"Ben_Blenny",
	"Robot_police_officer",
	"Robot_Mantis",
	"Captain_Magma",
	"Pyrite_Ponderer",
	"Hand_creature",
	"Bikini_Bottom_Mens_Choir",
	"Snail_13",
	"Manatee",
	"Kid_fish",
	"Grand_Dad_Plankton",
	"Incidental_CM19",
	"Bully_snail",
	"Spike",
	"Orange_snail",
	"Mary",
	"Ugly_snail",
	"Billy",
	"How_to_Open_Things",
	"Randy_Cheeks",
	"Singing_cows",
	"Bullfrog",
	"Rrarrg",
	"Mermaid_Teenager_incidentals",
	"Money",
	"Madame_Hagfish",
	"Green_kid",
	"Orange_kid",
	"Ma_Angler",
	"Y_incidentals",
	"Cletus",
	"Buford",
	"Incidental_Y3",
	"Incidental_Y4",
	"Incidental_Y5",
	"Incidental_Y6",
	"Incidental_Y8",
	"Incidental_Y10",
	"Incidental_Y11",
	"Incidental_Y12",
	"Incidental_Y13",
	"Incidental_Y14",
	"Incidental_Y15",
	"Incidental_Y17",
	"Jethra",
	"Incidental_Y19",
	"Uncle_Belcher",
	"Betsy",
	"Unknown_Y_1",
	"Unknown_Y_2",
	"Unknown_Y_3",
	"Unknown_Y_4",
	"Unknown_Y_5",
	"Unknown_Y_6",
	"Slimy_trash_can_creatures",
	"Ancient_warrior",
	"Orin_J_Ruffy",
	"Conductor",
	"Jewel_Triplets_Gang",
	"Friendly_lady",
	"Keystone_cops",
	"Teller",
	"SpongeBobs_grandson",
	"Patrick_clones",
	"Fish_with_plate",
	"Enchanted_tikis",
	"Howard_Blandy",
	"Grandma_SquarePants_house",
	"Earworm",
	"Bartender",
	"Patrick_Not_Star",
	"Club_Shell",
	"Mr_Sea_Chicken",
	"Announcer",
	"Sea_Chicken_Shack_cashier",
	"Sea_whelks",
	"Mother_sea_whelk",
	"Simple_Ton",
	"Bubble_Patrick",
	"Glove_World",
	"Crawly_clown",
	"Howard",
	"Squid_Love",
	"Squilvia",
	"Sam_Star",
	"Live_action_broccoli",
	"OWS_inspector",
	"Lampreys",
	"Ernesto_Blindfish",
	"Pearls_cyan_friend",
	"Incidental_118",
	"Tony_Fast_Sr",
	"Tony_Fast_Jr",
	"Street_racers",
	"Female_racer",
	"Male_racer",
	"Muscular_racer",
	"Baytona_Classic",
	"Pete_the_Rock",
	"Garbage_man",
	"Bikini_Bottom_Sanitation_Police",
	"Sheldon_J_Plankton",
	"Plankton_robot",
	"Cockney_worm",
	"Robot_worms",
	"Mr_Krabs_worms",
	"Abominable_snow_mollusk",
	"Beard",
	"Everybody_Aplomb_Now",
	"Sweetie_Scouts",
	"Fredrick_T_Nitpik",
	"Angry_Jack",
	"Giant_fruit_fly",
	"Travel_agent",
	"Fat_hairy_fish",
	"Ernest_Borgnine",
	"Bill",
	"Bank_robbers",
	"Lord_Poltergeist",
	"Donut_demon",
	"SpongeBob_demon",
	"Milkshake_gremlin",
	"Mermaid_Teenager_incidentals",
	"Teen_15s_boyfriend",
	"Bikini_Bottom_High_School",
	"Sandys_robots",
	"Fuzzy_Acorns",
	"Giant_Krabby_Patty",
	"Friendly_lady",
	"SnookiemsRaymond_the_WormFifi",
	"Krusty_Krab_cash_register",
	"Gordon_Plankton",
	"Puzzle_cube",
	"Shiny_Bubble",
	"Bikini_Bottom_Pillow_Foundry",
	"Fiasco",
	"Farfel_Bainbridge",
	"Curator",
	"Squidwards_scallop",
	"Jelliens",
	"Jellien_leader",
	"Jellien_clones",
	"Karen_Plankton_20",
	"Sir_Cecil",
	"Milk",
	"Glove_World_owner",
	"Weird_lady_fish",
	"Captain_Lutefisk",
	"The_Cackling_Cruiser",
	"Blowtorch",
	"The_Kruncher",
	"Divin_Bell_Dale",
	"Incidental_186",
	"Pet_Store",
	"Female_spokesmodel",
	"Bogus_Business_Bureau_agents",
	"Agent_Twirp",
	"Patty_Laddie",
	"Flankton",
	"ToyBob",
	"Elves",
	"Carolers",
	"Polar_bear",
	"Fake_Santa",
	"Seahorse",
	"Frankie",
	"Johnny",
	"Sea_tiger",
	"Spooty_Hooperfish",
	"Purple_old_lady",
	"Sweet_old_lady",
	"Fancy_guy",
	"Mr_Mailman",
	"State_officer",
	"Three_Headed_Jake",
	"Colonel_Carper",
	"Incidental_89B",
	"Incidental_117",
	"Drastic_Radicals",
	"Johnny_Krill",
	"Grand_Maul_Granny",
	"Not_Dead_Ted",
	"British_gentleman",
	"Mattress",
	"Earl_Cheeks",
	"Guinness_ORipley",
	"SpongeBobs_alarm_clock",
	"Nematodes",
	"Captain_Frostymug",
	"Milkshake_Academy_cadets",
	"Hotline",
	"Taxi_driver",
	"Big_dude",
	"Highway_Speed_Patrol",
	"Planktons_death_robot",
	"Unknown_old_fish",
	"Stranger",
	"Prisoner_incidentals",
	"Prisoner_2",
	"Light_blue_cellmate",
	"Prisoner_1",
	"Olive_green_cellmate",
	"Prisoner_6",
	"Prisoner_4",
	"Clerk",
	"Majestic_Sizzlemaster",
	"Analyzer",
	"SpongeBlob",
	"Bubbleman",
	"Mrs_Greenback",
	"Money_dragon",
	"Bank_manager",
	"Big_clam",
	"Spot",
	"Usher_1",
	"The_Fisherman",
	"Slasher_McGee",
	"Psychic",
	"Colored_ghost",
	"Rusty_Rickets",
	"Kenny_the_Cat",
	"Announcer",
	"Yeti_Krab",
	"Mister_WeinerMr_Weenie_Jr",
	"Pizza_Pete",
	"Señor_Taco",
	"Noodleman",
	"Weenie_goons",
	"Shelled_spider_like_creature",
	"Sal",
	"Bikini_Bottom_Construction_Company",
	"Widow_Duncan",
	"BusinessFish_12",
	"BusinessFish_13",
	"Stockholder_eel",
	"Jenkins",
	"Krabby_Patty_workers",
	"Simmy",
	"Tally",
	"Kelpy",
	"Walrus_toys",
	"Beary",
	"Sea_unicorn",
	"Captain_Scarfish",
	"Octopus_sailor",
	"SpongeBob_guard",
	"Pirate_queen",
	"Esmerelda",
	"Bob_Barnacle",
	"Sea_snail",
	"Baby_snails",
	"Mama_snail",
	"Dani",
	"Dani_Michaeli",
	"Commissioner",
	"Oswald_McNulty",
	"Patricks_taste_buds",
	"Mini_Brain_Patricks",
	"Teddy",
	"Crupski",
	"Charlton_Hawkfish",
	"Bikini_Bottom_Barnacles",
	"Sewer_snake",
	"Trouser_Troops",
	"Incidental_68",
	"Lady_fish",
	"Patrick_Corp",
	"Walter_Haddock",
	"Sea_bear",
	"Cashina",
	"Coral_Cuties",
	"Incidental_115",
	"Marina",
	"Nocturna",
	"Goth_fish",
	"Nixie",
	"Mr_Pepalino",
	"Goth_whale",
	"Bangles_and_Dangles_manager",
	"Beatrice",
	"Health_inspector",
	"Myrtle",
	"Dr_Manfish",
	"Hillbilly_couple",
	"The_Sharks",
	"Donnie",
	"Lonnie",
	"Ronnie",
	"Sharkface",
	"Jonnie",
	"Drink_vendor",
	"Bouncer",
	"The_Pods",
	"Internal_Affairs",
	"TV_producer",
	"Short_customer",
	"Mini_Patricks",
	"Isopod",
	"Nick_Fishkins",
	"Baby_worms",
	"Mr_Krabs_three_nephews",
	"Chinese_Food",
	"Don_Grouper",
	"Limia",
	"Baby_executive",
	"Barry_Goby",
	"Rob_Koi",
	"Old_executive",
	"Bubbles",
	"Whale",
	"Krusty_Krab_robots",
	"Robot_Patrick",
	"Robot_Squidward",
	"Shalmon",
	"Snail_monster",
	"Donut",
	"Mustard",
	"Food_Con",
	"Firefighters",
	"Mr_Stinky",
	"Big_lady",
	"Monster",
	"Carnie",
	"Dr_Mundane",
	"Baby_Tooth",
	"Seal_customer",
	"Mipsey_and_Pipsey",
	"Angry_old_timer",
	"Unnamed_kid",
	"Yellow_nurse",
	"Doctor_incidentals",
	"Doctor_3",
	"Doctor_4",
	"Doctor_6",
	"Doctor_8",
	"Doctor_7",
	"Doctor_9",
	"Doctor_10",
	"Doctor_11",
	"Doctor_12",
	"Doctor_13",
	"Doctor_14",
	"Doctor_15",
	"Doctor_16",
	"Steve",
	"Sea_chicken",
	"Prickles",
	"Lab_Squidward",
	"Anchovies",
	"Maestro_Mackerel",
	"Kid_Spikes",
	"Lady_Upturn_CCCXXXIII",
	"Music_School_Matron",
	"Kid_incidentals",
	"Incidental_150",
	"Incidental_151",
	"Incidental_153",
	"Musician_incidentals",
	"New_Fancy_1",
	"New_Fancy_2",
	"New_Fancy_3",
	"New_Fancy_4",
	"New_Fancy_5",
	"New_Fancy_6",
	"New_Fancy_7",
	"Octopus_dude",
	"Tuck_Tucker",
	"Unknown_BusinessFish_6",
	"Mr_Fitz",
	"Steve",
	"Molecular_Analyzer",
	"Sea_spider",
	"Finback_fish",
	"Robotic_horse",
	"King_Neptunes_trident",
	"Greek_chorus",
	"Kraken_mother",
	"Pacifier_monster",
	"Sea_urchin",
	"Incidental_161",
	"Incidental_162",
	"Shark_dad",
	"Sticky_Fins_Whiting",
	"Dorsal_Dan",
	"Crying_child",
	"Teddy_fish",
	"Ginger",
	"Incidental_91s_son",
	"Incidental_82s_son",
	"Incidental_89s_son",
	"Sea_snail",
	"Miners",
	"Tylosaurus",
	"Tanystropheus",
	"Even_more_elderly_customer",
	"Cindy",
	"Twin_sisters",
	"Ice_Cream_King",
	"Art_appraiser",
	"Snow_sponge",
	"Jojo",
	"Martians",
	"Dan_Southworth",
	"Hillbilly_couple",
	"Spongy_Spongy",
	"Criminal",
	"Incidental_7",
	"Spots_children",
	"Matilda",
	"Demolitions_puppy",
	"Acrobat_puppy",
	"Identical_twin_puppies",
	"Comic_relief_puppy",
	"Unknown_fancy_incidental",
	"Fred_Osmond_caricature_fish",
	"Brian_Morante_caricature_fish",
	"Spots_grandchildren",
	"Nurse_Helga_Schmerzen",
	"Moon_Gills",
	"Sunshine",
	"Crystal_Dave",
	"Old_lady",
	"The_Curse_of_Bikini_Bottom",
	"Squidward_the_Unfriendly_Ghost",
	"Acorn_monster",
	"Flying_Dutchmans_ghost_pirates",
	"Ol_Ribeye",
	"Rube_Goldfish",
	"Tour_guide",
	"Incidental_187",
	"Guy",
	"Little_girls",
	"Krabby_Patty_creatures",
	"Hipster_fish",
	"PM_incidentals",
	"Incidental_60",
	"Incidental_152",
	"Incidental_150",
	"Tom",
	"Incidental_PM5",
	"Incidental_82",
	"Old_Man_Walker",
	"Judy",
	"Incidental_13",
	"Incidental_PM10",
	"Incidental_42",
	"Incidental_PM12",
	"Incidental_21",
	"Incidental_30",
	"Incidental_PM15",
	"Incidental_16",
	"Incidental_PM17",
	"Incidental_9",
	"Incidental_PM19",
	"Victoria_Ellen",
	"Incidental_PM21",
	"Incidental_8",
	"Carol",
	"Incidental_PM24",
	"Incidental_PM25",
	"Mabel",
	"Incidental_11",
	"Incidental_PM28",
	"Incidental_PM29",
	"Trash_inspectors",
	"Doll",
	"Incidental_103",
	"Bunny_Wunny",
	"Female_sea_bunny",
	"Animal_control_fish",
	"Suburban_dad_doll",
	"Pyrite_Ponderer",
	"Jazz_Eel",
	"Um_Tentacles",
	"Loch_Ness_Monster",
	"Sand_witch",
	"Desert_sandwich",
	"Boxing_Begonia",
	"Taxi_driver",
	"Cuddle_Eat_Hugs",
	"Angler_fish",
	"Incidental_169",
	"Chatterbox_translation_collar",
	"Master_Marty",
	"Elephant_snail",
	"Clowns",
	"Little_clown",
	"Ringmaster",
	"Ringmasters_assistant",
	"Vendor",
	"Boss",
	"Coupe",
	"Boat_salesman_shark",
	"Marco",
	"Clarabelle",
	"Mortimer",
	"Kids_roughs_Adam_incidentals",
	"Incidental_34",
	"Little_girl_fish",
	"Senior_incidentals",
	"Senior_2",
	"Incidental_179",
	"Incidental_180",
	"Senior_7",
	"Unknown_Senior_1",
	"Unknown_Senior_2",
	"Unknown_Senior_3",
	"Unknown_Senior_4",
	"Unknown_Senior_5",
	"BunnyBunnsKids_incidentals",
	"Incidental_163",
	"Elwood",
	"BunnyBunnsKids_3",
	"Incidental_168",
	"BunnyBunnsKids_6",
	"BunnyBunnsKids_7",
	"BunnyBunnsKids_10",
	"BunnyBunnsKids_11",
	"BunnyBunnsKids_13",
	"Incidental_160",
	"Incidental_1B",
	"BunnyBunnsKids_16",
	"BunnyBunnsKids_17",
	"BunnyBunnsKids_18",
	"BunnyBunnsKids_19",
	"BunnyBunnsKids_20",
	"BunnyBunnsKids_22",
	"Joshua",
	"Unknown_BunnyBunnsKids_1",
	"Unknown_BunnyBunnsKids_2",
	"Unknown_BunnyBunnsKids_3",
	"Unknown_BunnyBunnsKids_4",
	"Tiny_SpongeBob",
	"Tiny_Patrick",
	"Picture_framed_snails",
	"Doodle_Sandy",
	"Doodle_Squidward",
	"Doodle_Mr_Krabs",
	"Doodle_Gary",
	"Squeaky",
	"Doodle_Squeaky",
	"Old_coot",
	"Vincent_Waller",
	"Mini_DoodleBobs",
	"Krabby_Patty",
	"Baby_incidentals",
	"Harold",
	"Incidental_7",
	"Sadie",
	"Mama_Bass",
	"Fruit_man",
	"Incidental_172",
	"Incidental_175",
	"Incidental_176",
	"Lloyd",
	"Mr_What_Zit_Tooya",
	"Incidental_179",
	"Incidental_180",
	"Incidental_188",
	"No",
	"Harris",
	"Mother_in_law",
	"Electric_eye",
	"Convict",
	"Dr_Charley_Horse",
	"Nurse_Daisy_Bazooka",
	"Girl_scout",
	"Dr_Kelpington",
	"Dr_Kelpingtons_snail",
	"Patricks_organs",
	"Puppet_Squidward",
	"Mildred",
	"Incidental_167",
	"Hot_rod_dude",
	"Mummy",
	"Incidental_163",
	"Incidental_168",
	"Fangtooth_fish",
	"Dylan",
	"Unknown_Teen_1",
	"Unknown_Teen_2",
	"Unknown_Teen_3",
	"Unknown_Teen_4",
	"Unknown_Teen_5",
	"Unknown_Teen_6",
	"Eugene_H_Krabs",
	"Female_boss",
	"Trash_bot",
	"Copier",
	"Coffeemaker",
	"Soda_machine",
	"Microwave_oven",
	"Shredinator_3000",
	"Walter_the_Waiter",
	"Geppetto",
	"Pinocchio",
	"Conscience",
	"ChefBob",
	"Trash_inspectors",
	"Incidental_166",
	"Patricks_brain",
	"Sir_Urchin",
	"Snail_Fail",
	"Helen_the_Felon",
	"Judge",
	"Ma_Cheeks",
	"Storyboard_artist",
	"Adam_Paloian",
	"Squidina_Star",
	"Country_squirrel",
	"Mrs_Krabs",
	"Impound_worker",
	"Off_Model_SpongeBob",
	"Gnarly_Squid",
	"Money_Krabs",
	"Ideal_Plankton",
	"Virus",
	"Female_hick",
	"Hanna",
	"HB_incidentals",
	"Incidental_HB1",
	"Incidental_HB2",
	"Incidental_HB3",
	"Incidental_HB4",
	"Incidental_HB5",
	"Incidental_HB6",
	"Incidental_164",
	"Incidental_171",
	"Incidental_183",
	"Incidental_184",
	"Incidental_181",
	"Incidental_182",
	"Unnamed_purple_worm",
	"Chuck",
	"Incidental_207",
	"Incidental_210",
	"Incidental_213",
	"Jennifer",
	"Nipples_guy",
	"Antenna_fish",
	"Chunky_fish",
	"Phyllosoma",
	"Snipe_eel",
	"Multi_eyed_fish",
	"Goblin_shark_guy",
	"Three_eyed_anglerfish",
	"Surprise_fish",
	"Monster_anglerfish",
	"Organism",
	"Slug_lady",
	"Flat_fish",
	"Egg_fish",
	"Spiky_fin_fish",
	"Barreleye_fish",
	"Deep_red_jellyfish",
	"Immortal_jellyfish",
	"Comb_jelly",
	"Pink_see_through_fantasia",
	"Sucker",
	"Invisible_Stan",
	"Squidabeth",
	"Maitre_D",
	"Barry_Blobfish",
	"Adorable_bubble_child",
	"Gal_Pals",
	"Jelly_buzz_saws",
	"Giant_jellyfish",
	"Homeowner",
	"Rich_patron",
	"Mike_Bell",
	"Old_Man_Jenkins_barn",
	"Ol_Bessy",
	"Jellybee",
	"Worm_hogs",
	"Old_Man_Jenkins_house",
	"Aliens",
	"Marvin",
	"Alice_Wilson",
	"Unknown_purebred_snail",
	"Incidental_42",
	"Unknown_Snail_9",
	"Unknown_Snail_13",
	"Fred",
	"Lenny",
	"EHS_incidentals",
	"Incidental_EHS1",
	"Incidental_EHS2",
	"Incidental_EHS3",
	"Incidental_EHS4",
	"Eel",
	"Incidental_EHS6",
	"Incidental_20",
	"Incidental_EHS8",
	"Incidental_EHS9",
	"Big_lady",
	"Incidental_EHS11",
	"Incidental_EHS12",
	"Incidental_EHS13",
	"Incidental_EHS14",
	"Incidental_EHS15",
	"Incidental_EHS16",
	"Unknown_EHS_1",
	"FEMA",
	"Little_idiot",
	"Filthy_Muck",
	"Prisoner_2",
	"Prisoner_6",
	"Lady_Upturns_snail",
	"Sea_chimps",
	"Sea_chimp_king",
	"Sea_chimp_child",
	"Old_sea_chimp_lady",
	"The_Takeoverer",
	"Incidental_174",
	"Teen_B7",
	"Ms_Mayor",
	"Business_fish",
	"Drizzle",
	"Drizzles_parents",
	"Drizzle_Jr",
	"Gale_Doppler",
	"Anchor_Man",
	"Firejellies",
	"Suburban_dad_doll",
	"Swamp",
	"Hoodoo_Guru_the_Voodoo_Villain",
	"Luther",
	"Wonder_Whale",
	"PlanKrab",
	"Red_PlanKrab",
	"Green_PlanKrab",
	"Hairball",
	"Money",
	"Macadamia",
	"Hazelnut",
	"Pistachio",
	"Rosy_Cheeks",
	"Woolly_mollusk",
	"Museum_curator",
	"Art_restorer",
	"Art_critic",
	"Starfish_mummy",
	"SpongeTom",
	"Chip_I",
	"Chip_II_Plankton",
	"Stork_drone",
	"Machine_1",
	"Machine_2",
	"Machine_3",
	"Weird_machine",
	"Mel",
	"Tony",
	"Lady_turtle_1",
	"Lady_turtle_2",
	"Krabs_family",
	"Great_Grandpop_Krabs",
	"Great_Great_Great_Grandpa_Krabs",
	"Mr_Krabs_ancestors",
	"Jenkins_family",
	"Very_Old_Man_Jenkins_Sr",
	"Grandpa_Jenkins",
	"Great_Grandpa_Jenkins",
	"Great_Great_Grandpa_Jenkins",
	"Old_Man_Jenkins_ancestors",
	"CM_incidentals",
	"Incidental_CM1",
	"Incidental_CM2",
	"Incidental_CM3",
	"Incidental_CM4",
	"Incidental_CM5",
	"Incidental_CM6",
	"Incidental_CM7",
	"Incidental_CM8",
	"Incidental_CM9",
	"Incidental_CM10",
	"Bubba_fish",
	"Bryan_Flounder",
	"Harris",
	"Incidental_95",
	"Judy",
	"Incidental_CM25",
	"Flats_dad",
	"Unknown_CM_2",
	"Unknown_CM_3",
	"Unknown_CM_4",
	"Maitre_D",
	"Pirate_captain",
	"Teacher",
	"Jellyspotters",
	"Jellyfish_geek_G_incidentals",
	"Jellyfish_geek_G11",
	"Jellyfish_geek_G14",
	"Jellyfish_geek_G16",
	"Jellyfish_geek_G17",
	"Jellyfish_geek_G18",
	"JimBob",
	"Patrick_Star",
	"Mr_Manward",
	"Mr_Slabs",
	"Pearl_Slabs",
	"Mr_Charleston",
	"David_Hasselhoff",
	"Slappy_Laszlo",
	"Brian_Morantes_daughter_caricature_fish",
	"Brian_Morantes_wife_caricature_fish",
	"Princess_Mindy",
	"Beanie_McBean",
	"Kel_Mitchell",
	"Jack_Griffo",
	"Daniella_Perkins",
	"Ephriam_Lopez",
	"Can",
	"Gorilla_boss",
	"Monkey_Middle_managers",
	"JoJo_Siwa",
	"Tiffany_Haddish",
	"John_Goodman",
	"RuPaul",
	"Rob_Gronkowski",
	"Victoria_Beckham",
	"The_SpongeBob_MusicalThe_Broadway_Musical_for_Everyone",
	"Gilbert_Gottfried",
	"Dog_walker",
	"Thomas_F_Wilson",
	"Pie_dragon",
	"Patricks_lover_fish",
	"Funny_lady",
	"Incidental_RL10",
	"Bathing_female",
	"Lady_Squidward",
	"Red_Mist_Squidward",
	"Realtor",
	"Rodger",
	"Giant_man",
	"Kaz",
	"RandomLand_Squidward",
	"RandomLand_SpongeBob",
	"RandomLand_Patrick",
	"Ramone_dinos",
	"Joshua",
	"Beefy_guy",
	"Blue_blob",
	"Scrubby_and_the_Cleaning_Crew",
	"SpongeBobs_slices",
	"Reginald_Goober",
	"Goofy_Manager",
	"Thief",
	"Grandma_ghost",
	"Woman",
	"FG_incidentals",
	"Harris",
	"Tom",
	"Incidental_41",
	"Incidental_67",
	"Incidental_49A",
	"Incidental_103",
	"Mr_What_Zit_Tooya",
	"Bryan_Flounder",
	"Steven",
	"Incidental_95",
	"Chum_Krabs",
	"Pizza_guy",
	"Doorman",
	"Lighthouse_Louie",
	"Snail_babies",
	"Timmy",
	"Tina",
	"Moose_snail",
	"Flibberty_Gibbet",
	"Saleslady",
	"Chum_monkey",
	"Zookeeper",
	"Sea_tiger",
	"Sea_elephant",
	"Giraffe",
	"Sea_baboons",
	"Sea_hippo",
	"Bubble_goat",
	"Bubble_giraffe",
	"Health_inspector",
	"Patrick_clones",
	"Creature",
	"Harry_the_Health_Hazard",
	"Snooty_tang",
	"Toddler",
	"Animatronic_Hieronymus_Glove",
	"Glove_robots",
	"Animatronic_guard_worm",
	"Robot_glove_guards",
	"Animatronic_old_man",
	"Hieronymus_Glove",
	"Glove_World_officers",
	"Queen_Elizafish_I",
	"Guard_gloves",
	"Hieronymus_Gloves_servants",
	"Claire_St_Claire_and_the_Low_Tides",
	"Claire_St_Claire",
	"Stan",
	"Photo_fish",
	"Orange_hat_fish",
	"SpongeBoy",
	"Sea_bunny",
	"Fire_marshal",
	"Lloyd",
	"Circus_Sea_Fleas",
	"Bummer_Dude_Action_Figures",
	"Aerobics_fish",
	"Sea_bear",
	"Clem_Clam",
	"Rock_T_Puss",
	"DJ_2_Sc00pz",
	"Bongos_Bear",
	"Butcher",
	"The_Executive_Treatment",
	"Narlene",
	"Nobby",
	"Sea_mule",
	"WillyBob",
	"Ma_Plankton",
	"Collective_Hive_Under_Master",
	"Beefy_chum",
	"Sea_gator",
	"Patchy_the_Pirate",
	"Potty_the_Parrot",
	"Killer_robot",
	"Guru",
	"Helen_the_Felon",
	"Olaf",
	"Salty_Spitoon_Guys_Big_Brudder",
	"Creepy_squid",
	"Dwayne_The_Puck_Orca",
	"Sardina_Sardiña",
	"Prisoner_2",
	"Spirit",
	"Bertie_Fitzpatrick",
	"C_incidentals",
	"Rea",
	"Roh",
	"SWAT_Team",
	"Limia",
	"Upturns_employees_incidentals",
	"Incidental_30",
	"Incidental_30",
	"Incidental_30A",
	"Upturns_employees_incidentals",
	"Incidental_30",
	"Incidental_30",
	"Incidental_30A",
	"Incidental_30A",
	"Incidental_30A",
	"Upturns_employees_incidentals",
	"Jody_Ann_Chovy",
	"BusinessFish_2",
	"Incidental_63",
	"Doctor_11",
	"QT_π",
	"Veterinarian",
	"Incidental_182",
	"Visual_aids",
	"Navy_incidentals",
	"Judge_incidentals",
	"Viking_incidentals",
	"A_incidentals",
	"Incidental_A7",
	"Incidental_A20",
	"Muscle_Fish_incidentals",
	"Biker_incidentals",
	"Creepy_squid",
	"Orca_kid",
	"Goth_whale",
	"Prawn",
	"Mister_WeinerMr_Weenie_Jr",
	"Notodoris",
	"The_Foot",
	"Frankensteins_gorilla",
	"Innkeeper",
	"Creepy_coachman",
	"Kidferatu",
	"Incidental_56",
	"Incidental_F4",
	"Incidental_EHS12",
	"Phantom_of_the_Opera",
	"Slappy_heads",
	"Slippy",
	"Dr_Calimari",
	"Barker",
	"SpongeBot",
	"RoboGary",
	"Pat_Tron",
	"SquidBot",
	"SquidBot_twin",
	"RoboKrabs",
	"Karen",
	"SpongeBots_alarm_clock_robot",
	"Bathroom_mirror_robot",
	"Krabby_Battery_employee_hat",
	"Mrs_Puff_robot",
	"Lady_Upturn_robot",
	"Sandroid",
	"PlankBot",
	"RoboLarry",
	"RoboRube",
	"Bubble_Bass_robot",
	"Mama_Bass_robot",
	"GrandPat_Star",
	"RobotInc_incidentals",
	"Incidental_41",
	"Incidental_18",
	"Incidental_14",
	"Incidental_60",
	"Incidental_20",
	"Tom",
	"Fred",
	"Incidental_2",
	"Incidental_7",
	"Incidental_8",
	"Incidental_11",
	"Incidental_13",
	"Incidental_15",
	"Incidental_16",
	"Incidental_21",
	"Carol",
	"Incidental_23",
	"Incidental_24",
	"Incidental_27",
	"Incidental_30A",
	"Lou",
	"Judy",
	"Sadie",
	"Incidental_67",
	"Old_Man_Walker",
	"Klopnod_elder_man_3",
	"Demon",
	"Money",
	"Cecil_Star",
	"Bunny_Star",
	"Cowboy_1",
	"Cowboy_2",
	"Wise_kraken",
	"Wally",
	"Construction_foreman",
	"Mrs_Sally_Spitoon",
	"Bruiser_shark",
	"Giant_trevally",
	"Mo",
	"Duck_family",
	"Hammerhead_juvenile_delinquent",
	"Mechanical_bull",
	"Slightly_crazed_moray_eel",
	"Tough_customer",
	"Passin_Jacks",
	"Taxi_driver_plankton",
	"Chubby_cop",
	"Saltwater_trees",
	"Saltwater_trees",
	"Saltwater_trees",
	"Saltwater_trees",
	"Saltwater_trees",
	"Saltwater_trees",
	"Saltwater_trees",
	"Tooth_Fairy",
	"Sneaky_Hermit",
	"Los_Diablos",
	"Incidental_30A",
	"Unknown_Snail_8",
	"Unknown_Snail_12",
	"Petunia",
	"Incidental_30A",
	"Incidental_30A",
	"Harris",
	"Teen_13",
	"Incidental_30",
	"Billy",
	"Monster_Island",
	"Deadly_monsters",
	"Giant_snail_monster",
	"Giant_teal_fish_monster",
	"Banana_monster",
	"Banana_baby",
	"Snake_monster",
	"Cyclists",
	"Cave_dwellers",
	"Food_Con_Castaways",
	"Mother_fish",
	"Incidental_C13B",
	"Primitive_SpongeBob",
	"Jellybee",
	"Football_player",
	"Fifi",
	"Music_cop_1",
	"Music_cop_2",
	"Lady",
	"Mrs_Sturgeon",
	"Fergus",
	"Nelly",
	"Otto",
	"The_Maestro",
	"Captain_SpongeHab",
	"Fishmael_Tentacles",
	"Capn_A_Krabs",
	"Planky",
	"Pat_Buck_Star",
	"Dopey_Dick",
	"SpongeGoose",
	"SquidHarp",
	"Jack_Plankton",
	"Giant_Krabs",
	"Clockwork_Karen_Plankton",
	"Biddy_Sitting",
	"Incidental_41",
	"Incidental_63",
	"Steve",
	"Old_Mrs_Perkins",
	"Guru_Greasetrap",
	"Sea_bunny",
	"Mermaid_Man",
	"PatSlug",
	"Barnacle_Boy",
	"SquidUrchin",
	"BunnyKrabs",
	"SpongeBobs_pool",
	"Mailman",
	"Delivery_man",
	"Crowd_1",
	"Crowd_1B",
	"Crowd_2",
	"Crowd_2B",
	"Crowd_3",
	"Crowd_3B",
	"Bubbles_McGuppy",
	"Ringmaster_Mudkrab",
	"Kid",
	"Mom",
	"Dad",
	"Motorcycle_guy",
	"Old_Man_Jenkins_Jr",
	"Giraffe",
	"Pecan_Sandy",
	"Earth",
	"Security_ninjas",
	"Sadie",
	"Fondue_man",
	"Female_Fry_Cook_Games_competitor",
	"Ajax_Magee",
	"Surface_World_Pizza_chef",
	"Baby",
	"Pigulon",
	"Box_repairman",
	"Dinosaur",
	"Jungle_spider",
	"Sea_snake",
	"Sea_panther",
	"Cletus_Plankton",
	"Gordon_Plankton",
	"Regigilled",
	"Worm_hogs",
	"Sparklenose",
	"Lucky",
	"Poison_fish",
	"Rolly",
	"Percival_Rockhound",
	"Suzie_Groove",
	"Quarter_guy",
	"Breakfast_Magic",
	"Breakfast_monster",
	"Scallops_and_clams",
	"SpongeBox",
	"Plankton_20",
	"P_1000",
	"Kamp_Koral_SpongeBobs_Under_Years",
	"Ma_Narwhal",
	"Pa_Narwhal",
	"Jellybee",
	"Jeff_Jellyson",
	"Fabrica_Olay",
	"Miss_Marigold",
	"Moon_jelly",
	"Incidental_C14",
	"SpongeBob_SquarePants",
	"Steve",
	"Harvey",
	"Jimmy_Blobfish",
	"Preda_Tory",
	"Roxy",
	"Tall_Tail",
	"Squeakers_the_Clown",
	"Sea_baboons",
	"Sammy_Suckerfish",
	"Moppy",
	"Turtle",
	"Restaurant_manager",
	"Incidental_95",
}
